/* ============================================================
   YILKI GAMES — çok dilli metin katmanı

   Diller oyunla birebir aynı: tr en es de fr it pt ru zh ja

   KULLANIM: HTML'e data-i18n="anahtar" koy. İçinde etiket geçen
   metinler (<em>, <strong>, <br>) data-i18n-html ile yazılır —
   ikisini karıştırmak metni ekrana etiketleriyle basar.

   Eksik anahtar hata vermez: o dilde İngilizcesi görünür.
   ============================================================ */

var DILLER = {
  tr: "Türkçe",
  en: "English",
  es: "Español",
  de: "Deutsch",
  fr: "Français",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  zh: "中文",
  ja: "日本語",
};

var VARSAYILAN = "en";

var METIN = {
  tr: {
    "nav.games": "Oyunlar",
    "nav.support": "Destek",
    "foot.studio": "Stüdyo",
    "foot.help": "Yardım",
    "foot.join": "Bize katıl",
    "foot.portfolio": "Portfolyo gönder",
    "foot.legal": "Yasal",
    "foot.privacy": "Gizlilik Politikası",
    "foot.terms": "Kullanım Şartları",
    "hero.eyebrow": "Bağımsız oyun stüdyosu",
    "hero.title": "Küçük kurallar,<br />derin <em>oyunlar</em>.",
    "hero.sub": "Türkiye'de kurulu bağımsız bir oyun stüdyosuyuz. Öğrenmesi bir dakika, ustalaşması aylar süren oyunlar yapıyoruz.",
    "hero.cta": "Oyunları gör",
    "games.title": "Oyunlar",
    "games.note": "Dört yapım",
    "games.mobile": "Mobil",
    "games.pc": "PC",
    "badge.live": "Yayında",
    "badge.dev": "Geliştiriliyor",
    "badge.soon": "Yakında",
    "xoxd.genre": "Sıra tabanlı strateji",
    "xoxd.desc": "Tanıdık bir tahta, hiç oynamadığın bir kural. Her tur X mi O mu koyacağına sen karar veriyorsun — iki sembol de senin.",
    "xoxd.link": "Oyunu incele",
    "inklash.genre": "2B dövüş",
    "inklash.desc": "Hızlı, sert, tek dokunuşluk çarpışmalar.",
    "survive.genre": "Hayat simülasyonu",
    "survive.desc": "Bir hayatı baştan kur. Her karar bir sonrakini belirliyor.",
    "bit.genre": "Ticaret simülasyonu",
    "bit.desc": "Tezgâhını kur, pazarlığı öğren, semtin en iyisi ol.",
    "x.back": "Tüm oyunlar",
    "x.eyebrow": "Yayında · Android",
    "x.sub": "Tanıdık bir tahta, hiç oynamadığın bir kural.",
    "x.cta": "Google Play'de indir",
    "x.rule.label": "Tek kural",
    "x.rule.title": "İki sembol de senin.",
    "x.rule.p1": "Klasik XOX'ta sen X'sin, rakibin O. Burada öyle değil. Her turda hangisini koyacağına <strong>sen</strong> karar veriyorsun.",
    "x.rule.p2": "Tahtada beliren her <strong>X-O-X</strong> dizisi sana puan yazıyor. Yani saldırıyla savunma aynı hamlede birleşiyor: kendine dizi kurarken rakibine de kapı açıyorsun. Öğrenmesi bir dakika.",
    "x.demo.hint": "Dene — hücrelere dokun",
    "x.demo.score": "puan",
    "x.demo.clear": "Temizle",
    "x.modes.title": "Dört mod",
    "x.modes.note": "Aynı kural, dört yol",
    "x.mode1.t": "Sıralı",
    "x.mode1.d": "Rastgele rakiple eşleş, puan topla, rütbe atla. Puan ve rütbe hesabı sunucuda yapılıyor.",
    "x.mode2.t": "Kaos",
    "x.mode2.d": "Rastgele üretilen engelli tahtalar. Ezber yok, her maç yeni bir şekil.",
    "x.mode3.t": "Meydan okuma",
    "x.mode3.d": "Yirmi bölüm. Çapraz sayma, ayna, sis, körlük — her bölüm kuralı bir yerinden büküyor.",
    "x.mode4.t": "Tek oyuncu",
    "x.mode4.d": "İnternetsiz oynanır. Bot üç zorlukta; kolayı ısınma, zoru gerçekten zor.",
    "x.feat.title": "Kutunun içinde",
    "x.feat.1": "Arkadaş listesi, sohbet ve maç daveti",
    "x.feat.2": "Sıralama tablosu ve rütbeler",
    "x.feat.3": "Avatar ve arka plan koleksiyonu",
    "x.feat.4": "On dil desteği",
    "x.feat.5": "Google Play ile tek dokunuş giriş",
    "x.feat.6": "Premium ile reklamsız oyun",
  },

  en: {
    "nav.games": "Games",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Help",
    "foot.join": "Join us",
    "foot.portfolio": "Send your portfolio",
    "foot.legal": "Legal",
    "foot.privacy": "Privacy Policy",
    "foot.terms": "Terms of Service",
    "hero.eyebrow": "Independent game studio",
    "hero.title": "Small rules,<br />deep <em>games</em>.",
    "hero.sub": "We are an independent game studio based in Türkiye. We make games that take a minute to learn and months to master.",
    "hero.cta": "See the games",
    "games.title": "Games",
    "games.note": "Four titles",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Out now",
    "badge.dev": "In development",
    "badge.soon": "Coming soon",
    "xoxd.genre": "Turn-based strategy",
    "xoxd.desc": "A familiar board, a rule you have not played before. Each turn you decide whether to place X or O — both symbols are yours.",
    "xoxd.link": "View the game",
    "inklash.genre": "2D combat",
    "inklash.desc": "Fast, sharp, one-touch clashes.",
    "survive.genre": "Life simulation",
    "survive.desc": "Build a life from scratch. Every decision shapes the next one.",
    "bit.genre": "Trading simulation",
    "bit.desc": "Set up your stall, learn to haggle, become the best in the district.",
    "x.back": "All games",
    "x.eyebrow": "Out now · Android",
    "x.sub": "A familiar board, a rule you have not played before.",
    "x.cta": "Get it on Google Play",
    "x.rule.label": "One rule",
    "x.rule.title": "Both symbols are yours.",
    "x.rule.p1": "In classic tic-tac-toe you are X and your opponent is O. Not here. Every turn, <strong>you</strong> decide which one to place.",
    "x.rule.p2": "Every <strong>X-O-X</strong> line that appears on the board scores for you. Attack and defence collapse into a single move: building a line for yourself opens a door for your opponent. A minute to learn.",
    "x.demo.hint": "Try it — tap the cells",
    "x.demo.score": "points",
    "x.demo.clear": "Clear",
    "x.modes.title": "Four modes",
    "x.modes.note": "One rule, four ways",
    "x.mode1.t": "Ranked",
    "x.mode1.d": "Match with a random opponent, earn points, climb the ranks. Scoring is calculated on the server.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Randomly generated boards with obstacles. Nothing to memorise, a new shape every match.",
    "x.mode3.t": "Challenge",
    "x.mode3.d": "Twenty levels. Diagonals, mirrors, fog, blindness — each one bends the rule somewhere.",
    "x.mode4.t": "Single player",
    "x.mode4.d": "Plays offline. Three bot difficulties; easy is a warm-up, hard is genuinely hard.",
    "x.feat.title": "In the box",
    "x.feat.1": "Friends list, chat and match invites",
    "x.feat.2": "Leaderboard and ranks",
    "x.feat.3": "Avatar and background collection",
    "x.feat.4": "Ten languages",
    "x.feat.5": "One-tap sign-in with Google Play",
    "x.feat.6": "Ad-free play with Premium",
  },

  es: {
    "nav.games": "Juegos",
    "nav.support": "Soporte",
    "foot.studio": "Estudio",
    "foot.help": "Ayuda",
    "foot.join": "Únete",
    "foot.portfolio": "Envía tu portafolio",
    "foot.legal": "Legal",
    "foot.privacy": "Política de privacidad",
    "foot.terms": "Condiciones de uso",
    "hero.eyebrow": "Estudio de videojuegos independiente",
    "hero.title": "Reglas pequeñas,<br />juegos <em>profundos</em>.",
    "hero.sub": "Somos un estudio independiente con sede en Türkiye. Hacemos juegos que se aprenden en un minuto y se dominan en meses.",
    "hero.cta": "Ver los juegos",
    "games.title": "Juegos",
    "games.note": "Cuatro títulos",
    "games.mobile": "Móvil",
    "games.pc": "PC",
    "badge.live": "Disponible",
    "badge.dev": "En desarrollo",
    "badge.soon": "Próximamente",
    "xoxd.genre": "Estrategia por turnos",
    "xoxd.desc": "Un tablero conocido, una regla que no has jugado. En cada turno decides si pones X u O: los dos símbolos son tuyos.",
    "xoxd.link": "Ver el juego",
    "inklash.genre": "Combate 2D",
    "inklash.desc": "Choques rápidos, duros, de un solo toque.",
    "survive.genre": "Simulación de vida",
    "survive.desc": "Construye una vida desde cero. Cada decisión marca la siguiente.",
    "bit.genre": "Simulación de comercio",
    "bit.desc": "Monta tu puesto, aprende a regatear, sé el mejor del barrio.",
    "x.back": "Todos los juegos",
    "x.eyebrow": "Disponible · Android",
    "x.sub": "Un tablero conocido, una regla que no has jugado.",
    "x.cta": "Consíguelo en Google Play",
    "x.rule.label": "Una regla",
    "x.rule.title": "Los dos símbolos son tuyos.",
    "x.rule.p1": "En el tres en raya clásico tú eres X y tu rival es O. Aquí no. En cada turno decides <strong>tú</strong> cuál colocar.",
    "x.rule.p2": "Cada línea <strong>X-O-X</strong> que aparece en el tablero te da puntos. Ataque y defensa se juntan en un mismo movimiento: al construir tu línea le abres la puerta al rival. Un minuto para aprenderlo.",
    "x.demo.hint": "Pruébalo — toca las casillas",
    "x.demo.score": "puntos",
    "x.demo.clear": "Limpiar",
    "x.modes.title": "Cuatro modos",
    "x.modes.note": "Una regla, cuatro caminos",
    "x.mode1.t": "Clasificatoria",
    "x.mode1.d": "Enfréntate a un rival al azar, suma puntos, sube de rango. El cálculo se hace en el servidor.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tableros generados al azar con obstáculos. Nada que memorizar, una forma nueva cada partida.",
    "x.mode3.t": "Desafío",
    "x.mode3.d": "Veinte niveles. Diagonales, espejos, niebla, ceguera: cada uno tuerce la regla por algún lado.",
    "x.mode4.t": "Un jugador",
    "x.mode4.d": "Se juega sin conexión. Tres dificultades; la fácil es un calentamiento, la difícil es difícil de verdad.",
    "x.feat.title": "En la caja",
    "x.feat.1": "Lista de amigos, chat e invitaciones",
    "x.feat.2": "Clasificación y rangos",
    "x.feat.3": "Colección de avatares y fondos",
    "x.feat.4": "Diez idiomas",
    "x.feat.5": "Inicio de sesión con Google Play",
    "x.feat.6": "Sin anuncios con Premium",
  },

  de: {
    "nav.games": "Spiele",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Hilfe",
    "foot.join": "Mitmachen",
    "foot.portfolio": "Portfolio senden",
    "foot.legal": "Rechtliches",
    "foot.privacy": "Datenschutzerklärung",
    "foot.terms": "Nutzungsbedingungen",
    "hero.eyebrow": "Unabhängiges Spielestudio",
    "hero.title": "Kleine Regeln,<br />tiefe <em>Spiele</em>.",
    "hero.sub": "Wir sind ein unabhängiges Spielestudio in der Türkei. Wir machen Spiele, die man in einer Minute lernt und in Monaten meistert.",
    "hero.cta": "Spiele ansehen",
    "games.title": "Spiele",
    "games.note": "Vier Titel",
    "games.mobile": "Mobil",
    "games.pc": "PC",
    "badge.live": "Jetzt erhältlich",
    "badge.dev": "In Entwicklung",
    "badge.soon": "Demnächst",
    "xoxd.genre": "Rundenbasierte Strategie",
    "xoxd.desc": "Ein bekanntes Brett, eine Regel, die du noch nie gespielt hast. Jede Runde entscheidest du: X oder O — beide Zeichen gehören dir.",
    "xoxd.link": "Spiel ansehen",
    "inklash.genre": "2D-Kampf",
    "inklash.desc": "Schnelle, harte Zusammenstöße mit einem Tipp.",
    "survive.genre": "Lebenssimulation",
    "survive.desc": "Bau ein Leben von Grund auf. Jede Entscheidung prägt die nächste.",
    "bit.genre": "Handelssimulation",
    "bit.desc": "Bau deinen Stand auf, lerne zu feilschen, werde der Beste im Viertel.",
    "x.back": "Alle Spiele",
    "x.eyebrow": "Jetzt erhältlich · Android",
    "x.sub": "Ein bekanntes Brett, eine Regel, die du noch nie gespielt hast.",
    "x.cta": "Bei Google Play holen",
    "x.rule.label": "Eine Regel",
    "x.rule.title": "Beide Zeichen gehören dir.",
    "x.rule.p1": "Beim klassischen Tic-Tac-Toe bist du X und dein Gegner O. Hier nicht. In jeder Runde entscheidest <strong>du</strong>, welches du setzt.",
    "x.rule.p2": "Jede <strong>X-O-X</strong>-Reihe auf dem Brett bringt dir Punkte. Angriff und Verteidigung fallen in einen Zug zusammen: Wer sich eine Reihe baut, öffnet dem Gegner eine Tür. In einer Minute gelernt.",
    "x.demo.hint": "Probier's — tippe die Felder an",
    "x.demo.score": "Punkte",
    "x.demo.clear": "Leeren",
    "x.modes.title": "Vier Modi",
    "x.modes.note": "Eine Regel, vier Wege",
    "x.mode1.t": "Rangliste",
    "x.mode1.d": "Triff auf zufällige Gegner, sammle Punkte, steig im Rang auf. Die Wertung läuft auf dem Server.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Zufällig erzeugte Bretter mit Hindernissen. Nichts zum Auswendiglernen, jede Partie eine neue Form.",
    "x.mode3.t": "Herausforderung",
    "x.mode3.d": "Zwanzig Level. Diagonalen, Spiegel, Nebel, Blindheit — jedes biegt die Regel an einer Stelle.",
    "x.mode4.t": "Einzelspieler",
    "x.mode4.d": "Läuft offline. Drei Bot-Stufen; leicht ist Aufwärmen, schwer ist wirklich schwer.",
    "x.feat.title": "Im Paket",
    "x.feat.1": "Freundesliste, Chat und Spieleinladungen",
    "x.feat.2": "Bestenliste und Ränge",
    "x.feat.3": "Avatar- und Hintergrundsammlung",
    "x.feat.4": "Zehn Sprachen",
    "x.feat.5": "Anmeldung mit einem Tipp über Google Play",
    "x.feat.6": "Werbefrei mit Premium",
  },

  fr: {
    "nav.games": "Jeux",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Aide",
    "foot.join": "Nous rejoindre",
    "foot.portfolio": "Envoyer ton portfolio",
    "foot.legal": "Mentions légales",
    "foot.privacy": "Politique de confidentialité",
    "foot.terms": "Conditions d'utilisation",
    "hero.eyebrow": "Studio de jeux indépendant",
    "hero.title": "Des règles simples,<br />des jeux <em>profonds</em>.",
    "hero.sub": "Nous sommes un studio indépendant basé en Türkiye. Nous faisons des jeux qui s'apprennent en une minute et se maîtrisent en des mois.",
    "hero.cta": "Voir les jeux",
    "games.title": "Jeux",
    "games.note": "Quatre titres",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponible",
    "badge.dev": "En développement",
    "badge.soon": "Bientôt",
    "xoxd.genre": "Stratégie au tour par tour",
    "xoxd.desc": "Un plateau connu, une règle que tu n'as jamais jouée. À chaque tour, tu choisis X ou O — les deux symboles sont à toi.",
    "xoxd.link": "Voir le jeu",
    "inklash.genre": "Combat 2D",
    "inklash.desc": "Des affrontements rapides et secs, en un seul toucher.",
    "survive.genre": "Simulation de vie",
    "survive.desc": "Construis une vie depuis zéro. Chaque décision décide de la suivante.",
    "bit.genre": "Simulation de commerce",
    "bit.desc": "Monte ton stand, apprends à marchander, deviens le meilleur du quartier.",
    "x.back": "Tous les jeux",
    "x.eyebrow": "Disponible · Android",
    "x.sub": "Un plateau connu, une règle que tu n'as jamais jouée.",
    "x.cta": "Télécharger sur Google Play",
    "x.rule.label": "Une seule règle",
    "x.rule.title": "Les deux symboles sont à toi.",
    "x.rule.p1": "Au morpion classique, tu es X et ton adversaire O. Ici, non. À chaque tour, c'est <strong>toi</strong> qui choisis lequel poser.",
    "x.rule.p2": "Chaque ligne <strong>X-O-X</strong> qui apparaît sur le plateau te rapporte des points. L'attaque et la défense se confondent en un seul coup : en te construisant une ligne, tu ouvres une porte à l'adversaire. Une minute pour comprendre.",
    "x.demo.hint": "Essaie — touche les cases",
    "x.demo.score": "points",
    "x.demo.clear": "Effacer",
    "x.modes.title": "Quatre modes",
    "x.modes.note": "Une règle, quatre chemins",
    "x.mode1.t": "Classée",
    "x.mode1.d": "Affronte un adversaire au hasard, gagne des points, monte en rang. Le calcul se fait sur le serveur.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Plateaux générés au hasard avec des obstacles. Rien à mémoriser, une forme nouvelle à chaque partie.",
    "x.mode3.t": "Défi",
    "x.mode3.d": "Vingt niveaux. Diagonales, miroirs, brouillard, cécité — chacun tord la règle quelque part.",
    "x.mode4.t": "Solo",
    "x.mode4.d": "Se joue hors ligne. Trois niveaux de bot ; le facile est un échauffement, le difficile est vraiment difficile.",
    "x.feat.title": "Dans la boîte",
    "x.feat.1": "Liste d'amis, chat et invitations",
    "x.feat.2": "Classement et rangs",
    "x.feat.3": "Collection d'avatars et de fonds",
    "x.feat.4": "Dix langues",
    "x.feat.5": "Connexion en un toucher avec Google Play",
    "x.feat.6": "Sans publicité avec Premium",
  },

  it: {
    "nav.games": "Giochi",
    "nav.support": "Supporto",
    "foot.studio": "Studio",
    "foot.help": "Aiuto",
    "foot.join": "Unisciti a noi",
    "foot.portfolio": "Invia il portfolio",
    "foot.legal": "Note legali",
    "foot.privacy": "Informativa sulla privacy",
    "foot.terms": "Termini di servizio",
    "hero.eyebrow": "Studio di giochi indipendente",
    "hero.title": "Regole piccole,<br />giochi <em>profondi</em>.",
    "hero.sub": "Siamo uno studio indipendente con sede in Türkiye. Facciamo giochi che si imparano in un minuto e si padroneggiano in mesi.",
    "hero.cta": "Guarda i giochi",
    "games.title": "Giochi",
    "games.note": "Quattro titoli",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponibile",
    "badge.dev": "In sviluppo",
    "badge.soon": "In arrivo",
    "xoxd.genre": "Strategia a turni",
    "xoxd.desc": "Una tavola familiare, una regola che non hai mai giocato. Ogni turno decidi tu se mettere X o O: entrambi i simboli sono tuoi.",
    "xoxd.link": "Guarda il gioco",
    "inklash.genre": "Combattimento 2D",
    "inklash.desc": "Scontri rapidi e secchi, con un solo tocco.",
    "survive.genre": "Simulazione di vita",
    "survive.desc": "Costruisci una vita da zero. Ogni scelta determina la successiva.",
    "bit.genre": "Simulazione di commercio",
    "bit.desc": "Monta il banco, impara a contrattare, diventa il migliore del quartiere.",
    "x.back": "Tutti i giochi",
    "x.eyebrow": "Disponibile · Android",
    "x.sub": "Una tavola familiare, una regola che non hai mai giocato.",
    "x.cta": "Scarica su Google Play",
    "x.rule.label": "Una regola",
    "x.rule.title": "Entrambi i simboli sono tuoi.",
    "x.rule.p1": "Nel tris classico tu sei X e l'avversario è O. Qui no. A ogni turno decidi <strong>tu</strong> quale mettere.",
    "x.rule.p2": "Ogni sequenza <strong>X-O-X</strong> che compare sulla tavola ti dà punti. Attacco e difesa si fondono in una sola mossa: mentre costruisci la tua linea, apri una porta all'avversario. Si impara in un minuto.",
    "x.demo.hint": "Prova — tocca le caselle",
    "x.demo.score": "punti",
    "x.demo.clear": "Pulisci",
    "x.modes.title": "Quattro modalità",
    "x.modes.note": "Una regola, quattro strade",
    "x.mode1.t": "Classificata",
    "x.mode1.d": "Sfida un avversario casuale, accumula punti, sali di grado. Il calcolo avviene sul server.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tavole generate a caso con ostacoli. Niente da memorizzare, una forma nuova ogni partita.",
    "x.mode3.t": "Sfida",
    "x.mode3.d": "Venti livelli. Diagonali, specchi, nebbia, cecità: ognuno piega la regola da qualche parte.",
    "x.mode4.t": "Giocatore singolo",
    "x.mode4.d": "Si gioca offline. Tre difficoltà; la facile è riscaldamento, la difficile è davvero difficile.",
    "x.feat.title": "Nella scatola",
    "x.feat.1": "Lista amici, chat e inviti alle partite",
    "x.feat.2": "Classifica e gradi",
    "x.feat.3": "Collezione di avatar e sfondi",
    "x.feat.4": "Dieci lingue",
    "x.feat.5": "Accesso con un tocco tramite Google Play",
    "x.feat.6": "Senza pubblicità con Premium",
  },

  pt: {
    "nav.games": "Jogos",
    "nav.support": "Suporte",
    "foot.studio": "Estúdio",
    "foot.help": "Ajuda",
    "foot.join": "Junte-se a nós",
    "foot.portfolio": "Envie seu portfólio",
    "foot.legal": "Jurídico",
    "foot.privacy": "Política de Privacidade",
    "foot.terms": "Termos de Uso",
    "hero.eyebrow": "Estúdio de jogos independente",
    "hero.title": "Regras pequenas,<br />jogos <em>profundos</em>.",
    "hero.sub": "Somos um estúdio independente sediado na Türkiye. Fazemos jogos que se aprendem em um minuto e se dominam em meses.",
    "hero.cta": "Ver os jogos",
    "games.title": "Jogos",
    "games.note": "Quatro títulos",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponível",
    "badge.dev": "Em desenvolvimento",
    "badge.soon": "Em breve",
    "xoxd.genre": "Estratégia por turnos",
    "xoxd.desc": "Um tabuleiro conhecido, uma regra que você nunca jogou. A cada turno você decide se coloca X ou O — os dois símbolos são seus.",
    "xoxd.link": "Ver o jogo",
    "inklash.genre": "Combate 2D",
    "inklash.desc": "Choques rápidos e secos, com um toque só.",
    "survive.genre": "Simulação de vida",
    "survive.desc": "Construa uma vida do zero. Cada decisão define a próxima.",
    "bit.genre": "Simulação de comércio",
    "bit.desc": "Monte sua banca, aprenda a pechinchar, seja o melhor do bairro.",
    "x.back": "Todos os jogos",
    "x.eyebrow": "Disponível · Android",
    "x.sub": "Um tabuleiro conhecido, uma regra que você nunca jogou.",
    "x.cta": "Baixar no Google Play",
    "x.rule.label": "Uma regra",
    "x.rule.title": "Os dois símbolos são seus.",
    "x.rule.p1": "No jogo da velha clássico você é X e o adversário é O. Aqui não. A cada turno, <strong>você</strong> decide qual colocar.",
    "x.rule.p2": "Cada sequência <strong>X-O-X</strong> que aparece no tabuleiro te dá pontos. Ataque e defesa viram uma jogada só: ao montar sua linha, você abre uma porta para o adversário. Um minuto para aprender.",
    "x.demo.hint": "Experimente — toque nas casas",
    "x.demo.score": "pontos",
    "x.demo.clear": "Limpar",
    "x.modes.title": "Quatro modos",
    "x.modes.note": "Uma regra, quatro caminhos",
    "x.mode1.t": "Ranqueada",
    "x.mode1.d": "Enfrente um adversário aleatório, some pontos, suba de patente. O cálculo é feito no servidor.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tabuleiros gerados ao acaso com obstáculos. Nada para decorar, uma forma nova a cada partida.",
    "x.mode3.t": "Desafio",
    "x.mode3.d": "Vinte fases. Diagonais, espelhos, névoa, cegueira — cada uma torce a regra em algum ponto.",
    "x.mode4.t": "Um jogador",
    "x.mode4.d": "Joga offline. Três dificuldades; a fácil é aquecimento, a difícil é difícil de verdade.",
    "x.feat.title": "Na caixa",
    "x.feat.1": "Lista de amigos, chat e convites",
    "x.feat.2": "Classificação e patentes",
    "x.feat.3": "Coleção de avatares e fundos",
    "x.feat.4": "Dez idiomas",
    "x.feat.5": "Login com um toque pelo Google Play",
    "x.feat.6": "Sem anúncios com o Premium",
  },

  ru: {
    "nav.games": "Игры",
    "nav.support": "Поддержка",
    "foot.studio": "Студия",
    "foot.help": "Помощь",
    "foot.join": "Присоединяйся",
    "foot.portfolio": "Отправить портфолио",
    "foot.legal": "Правовая информация",
    "foot.privacy": "Политика конфиденциальности",
    "foot.terms": "Условия использования",
    "hero.eyebrow": "Независимая игровая студия",
    "hero.title": "Простые правила,<br />глубокие <em>игры</em>.",
    "hero.sub": "Мы независимая игровая студия из Турции. Делаем игры, которые осваиваются за минуту, а изучаются месяцами.",
    "hero.cta": "Посмотреть игры",
    "games.title": "Игры",
    "games.note": "Четыре проекта",
    "games.mobile": "Мобильные",
    "games.pc": "PC",
    "badge.live": "Уже вышла",
    "badge.dev": "В разработке",
    "badge.soon": "Скоро",
    "xoxd.genre": "Пошаговая стратегия",
    "xoxd.desc": "Знакомая доска и правило, в которое ты ещё не играл. Каждый ход ты сам решаешь, ставить X или O — оба символа твои.",
    "xoxd.link": "Об игре",
    "inklash.genre": "2D-бои",
    "inklash.desc": "Быстрые и жёсткие схватки в одно касание.",
    "survive.genre": "Симулятор жизни",
    "survive.desc": "Построй жизнь с нуля. Каждое решение определяет следующее.",
    "bit.genre": "Симулятор торговли",
    "bit.desc": "Поставь прилавок, научись торговаться, стань лучшим в районе.",
    "x.back": "Все игры",
    "x.eyebrow": "Уже вышла · Android",
    "x.sub": "Знакомая доска и правило, в которое ты ещё не играл.",
    "x.cta": "Скачать в Google Play",
    "x.rule.label": "Одно правило",
    "x.rule.title": "Оба символа твои.",
    "x.rule.p1": "В классических крестиках-ноликах ты X, а соперник O. Здесь не так. Каждый ход <strong>ты</strong> решаешь, что поставить.",
    "x.rule.p2": "Каждая последовательность <strong>X-O-X</strong> на доске приносит тебе очки. Атака и защита сливаются в один ход: строя свою линию, ты открываешь дверь сопернику. Разобраться — минута.",
    "x.demo.hint": "Попробуй — нажимай на клетки",
    "x.demo.score": "очков",
    "x.demo.clear": "Очистить",
    "x.modes.title": "Четыре режима",
    "x.modes.note": "Одно правило, четыре пути",
    "x.mode1.t": "Рейтинговый",
    "x.mode1.d": "Играй со случайным соперником, набирай очки, поднимай ранг. Подсчёт идёт на сервере.",
    "x.mode2.t": "Хаос",
    "x.mode2.d": "Случайные доски с препятствиями. Заучивать нечего, каждая партия — новая форма.",
    "x.mode3.t": "Испытание",
    "x.mode3.d": "Двадцать уровней. Диагонали, зеркала, туман, слепота — каждый где-то ломает правило.",
    "x.mode4.t": "Одиночная игра",
    "x.mode4.d": "Работает без интернета. Три уровня бота: лёгкий — разминка, сложный — действительно сложный.",
    "x.feat.title": "Что внутри",
    "x.feat.1": "Список друзей, чат и приглашения",
    "x.feat.2": "Таблица лидеров и ранги",
    "x.feat.3": "Коллекция аватаров и фонов",
    "x.feat.4": "Десять языков",
    "x.feat.5": "Вход одним касанием через Google Play",
    "x.feat.6": "Без рекламы с Премиумом",
  },

  zh: {
    "nav.games": "游戏",
    "nav.support": "支持",
    "foot.studio": "工作室",
    "foot.help": "帮助",
    "foot.join": "加入我们",
    "foot.portfolio": "发送作品集",
    "foot.legal": "法律",
    "foot.privacy": "隐私政策",
    "foot.terms": "使用条款",
    "hero.eyebrow": "独立游戏工作室",
    "hero.title": "规则很小，<br />游戏很<em>深</em>。",
    "hero.sub": "我们是一家位于土耳其的独立游戏工作室。我们做的游戏一分钟上手，几个月才能精通。",
    "hero.cta": "查看游戏",
    "games.title": "游戏",
    "games.note": "四款作品",
    "games.mobile": "移动端",
    "games.pc": "PC",
    "badge.live": "已上线",
    "badge.dev": "开发中",
    "badge.soon": "即将推出",
    "xoxd.genre": "回合制策略",
    "xoxd.desc": "熟悉的棋盘，从未玩过的规则。每回合由你决定下 X 还是 O——两个符号都是你的。",
    "xoxd.link": "查看游戏",
    "inklash.genre": "2D 格斗",
    "inklash.desc": "快速、凌厉、一触即发的对撞。",
    "survive.genre": "人生模拟",
    "survive.desc": "从零开始经营一段人生。每个决定都决定下一个。",
    "bit.genre": "交易模拟",
    "bit.desc": "支起摊位，学会讨价还价，成为街区最强。",
    "x.back": "全部游戏",
    "x.eyebrow": "已上线 · Android",
    "x.sub": "熟悉的棋盘，从未玩过的规则。",
    "x.cta": "在 Google Play 下载",
    "x.rule.label": "唯一规则",
    "x.rule.title": "两个符号都是你的。",
    "x.rule.p1": "在传统井字棋里你是 X，对手是 O。这里不是。每一回合都由<strong>你</strong>决定下哪一个。",
    "x.rule.p2": "棋盘上出现的每一条 <strong>X-O-X</strong> 都会为你计分。进攻和防守合成同一步：你在给自己连线的同时，也给对手开了一扇门。一分钟就能学会。",
    "x.demo.hint": "试试看——点击格子",
    "x.demo.score": "分",
    "x.demo.clear": "清空",
    "x.modes.title": "四种模式",
    "x.modes.note": "一条规则，四条路",
    "x.mode1.t": "排位",
    "x.mode1.d": "匹配随机对手，累积分数，提升段位。计分在服务器完成。",
    "x.mode2.t": "混沌",
    "x.mode2.d": "随机生成的带障碍棋盘。无需背板，每局都是新形状。",
    "x.mode3.t": "挑战",
    "x.mode3.d": "二十个关卡。对角线、镜像、迷雾、致盲——每关都在某处扭曲规则。",
    "x.mode4.t": "单人",
    "x.mode4.d": "可离线游玩。机器人分三档；简单是热身，困难是真的难。",
    "x.feat.title": "包含内容",
    "x.feat.1": "好友列表、聊天与对战邀请",
    "x.feat.2": "排行榜与段位",
    "x.feat.3": "头像与背景收藏",
    "x.feat.4": "十种语言",
    "x.feat.5": "通过 Google Play 一键登录",
    "x.feat.6": "高级版免广告",
  },

  ja: {
    "nav.games": "ゲーム",
    "nav.support": "サポート",
    "foot.studio": "スタジオ",
    "foot.help": "ヘルプ",
    "foot.join": "参加する",
    "foot.portfolio": "ポートフォリオを送る",
    "foot.legal": "法的情報",
    "foot.privacy": "プライバシーポリシー",
    "foot.terms": "利用規約",
    "hero.eyebrow": "インディーゲームスタジオ",
    "hero.title": "小さなルール、<br />深い<em>ゲーム</em>。",
    "hero.sub": "トルコを拠点とするインディーゲームスタジオです。覚えるのは一分、極めるのは数か月かかるゲームを作っています。",
    "hero.cta": "ゲームを見る",
    "games.title": "ゲーム",
    "games.note": "4タイトル",
    "games.mobile": "モバイル",
    "games.pc": "PC",
    "badge.live": "配信中",
    "badge.dev": "開発中",
    "badge.soon": "近日公開",
    "xoxd.genre": "ターン制ストラテジー",
    "xoxd.desc": "見慣れた盤に、遊んだことのないルール。毎ターン X と O のどちらを置くかは自分次第——どちらの記号もあなたのものです。",
    "xoxd.link": "ゲームを見る",
    "inklash.genre": "2D対戦アクション",
    "inklash.desc": "速く、鋭い、ワンタッチの斬り合い。",
    "survive.genre": "人生シミュレーション",
    "survive.desc": "人生をゼロから組み立てる。すべての選択が次を決めます。",
    "bit.genre": "商売シミュレーション",
    "bit.desc": "露店を構え、値切りを覚え、街で一番になろう。",
    "x.back": "すべてのゲーム",
    "x.eyebrow": "配信中 · Android",
    "x.sub": "見慣れた盤に、遊んだことのないルール。",
    "x.cta": "Google Play で入手",
    "x.rule.label": "ルールはひとつ",
    "x.rule.title": "どちらの記号もあなたのもの。",
    "x.rule.p1": "普通の三目並べでは自分が X、相手が O です。ここでは違います。毎ターン、どちらを置くかを決めるのは<strong>あなた</strong>です。",
    "x.rule.p2": "盤上にできた <strong>X-O-X</strong> の並びがすべて得点になります。攻めと守りが一手に重なる——自分の列を作ることが、相手にも道を開くのです。覚えるのは一分。",
    "x.demo.hint": "試してみよう — マスをタップ",
    "x.demo.score": "点",
    "x.demo.clear": "クリア",
    "x.modes.title": "4つのモード",
    "x.modes.note": "ひとつのルール、4つの遊び方",
    "x.mode1.t": "ランク戦",
    "x.mode1.d": "ランダムな相手と対戦し、ポイントを稼ぎ、ランクを上げる。集計はサーバー側で行われます。",
    "x.mode2.t": "カオス",
    "x.mode2.d": "障害物付きのランダム生成盤面。暗記は不要、毎試合が新しい形です。",
    "x.mode3.t": "チャレンジ",
    "x.mode3.d": "20ステージ。斜め、ミラー、霧、目隠し——それぞれがルールをどこかで曲げます。",
    "x.mode4.t": "シングルプレイ",
    "x.mode4.d": "オフラインで遊べます。ボットは3段階、簡単は肩慣らし、難しいは本当に難しい。",
    "x.feat.title": "収録内容",
    "x.feat.1": "フレンドリスト・チャット・対戦招待",
    "x.feat.2": "ランキングとランク",
    "x.feat.3": "アバターと背景のコレクション",
    "x.feat.4": "10言語対応",
    "x.feat.5": "Google Play でワンタップログイン",
    "x.feat.6": "プレミアムで広告なし",
  },
};
