/* ============================================================
   YILKI GAMES — çok dilli metin katmanı

   Diller oyunla birebir aynı: tr en es de fr it pt ru zh ja

   KULLANIM: HTML'e data-i18n="anahtar" koy. İçinde etiket geçen
   metinler (<em>, <strong>, <br>) data-i18n-html ile yazılır —
   ikisini karıştırmak metni ekrana etiketleriyle basar.

   Eksik anahtar hata vermez: o dilde İngilizcesi görünür.
   ============================================================ */

var DILLER = {
  tr: "Türkçe",
  en: "English",
  es: "Español",
  de: "Deutsch",
  fr: "Français",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  zh: "中文",
  ja: "日本語",
};

var VARSAYILAN = "en";

var METIN = {
  tr: {
    "nav.games": "Oyunlar",
    "nav.support": "Destek",
    "foot.studio": "Stüdyo",
    "foot.help": "Yardım",
    "foot.join": "Bize katıl",
    "foot.portfolio": "Portfolyo gönder",
    "foot.legal": "Yasal",
    "foot.privacy": "Gizlilik Politikası",
    "foot.terms": "Kullanım Şartları",
    "hero.eyebrow": "Bağımsız oyun stüdyosu",
    "hero.title": "Küçük kurallar,<br />derin <em>oyunlar</em>.",
    "hero.sub": "Türkiye'de kurulu bağımsız bir oyun stüdyosuyuz. Öğrenmesi bir dakika, ustalaşması aylar süren oyunlar yapıyoruz.",
    "hero.cta": "Oyunları gör",
    "games.title": "Oyunlar",
    "games.note": "Dört yapım",
    "games.mobile": "Mobil",
    "games.pc": "PC",
    "badge.live": "Yayında",
    "badge.dev": "Geliştiriliyor",
    "badge.soon": "Yakında",
    "xoxd.genre": "Sıra tabanlı strateji",
    "xoxd.desc": "Tanıdık bir tahta, hiç oynamadığın bir kural. Her tur X mi O mu koyacağına sen karar veriyorsun — iki sembol de senin.",
    "xoxd.link": "Oyunu incele",
    "inklash.genre": "2B dövüş",
    "inklash.desc": "Hızlı, sert, tek dokunuşluk çarpışmalar.",
    "survive.genre": "Hayat simülasyonu",
    "survive.desc": "Bir hayatı baştan kur. Her karar bir sonrakini belirliyor.",
    "bit.genre": "Ticaret simülasyonu",
    "bit.desc": "Tezgâhını kur, pazarlığı öğren, semtin en iyisi ol.",
    "x.back": "Tüm oyunlar",
    "x.eyebrow": "Yayında · Android",
    "x.sub": "Tanıdık bir tahta, hiç oynamadığın bir kural.",
    "x.cta": "Google Play'de indir",
    "x.rule.label": "Tek kural",
    "x.rule.title": "İki sembol de senin.",
    "x.rule.p1": "Klasik XOX'ta sen X'sin, rakibin O. Burada öyle değil. Her turda hangisini koyacağına <strong>sen</strong> karar veriyorsun.",
    "x.rule.p2": "Tahtada beliren her <strong>X-O-X</strong> dizisi sana puan yazıyor. Yani saldırıyla savunma aynı hamlede birleşiyor: kendine dizi kurarken rakibine de kapı açıyorsun. Öğrenmesi bir dakika.",
    "x.demo.hint": "Dene — hücrelere dokun",
    "x.demo.score": "puan",
    "x.demo.clear": "Temizle",
    "x.modes.title": "Dört mod",
    "x.modes.note": "Aynı kural, dört yol",
    "x.mode1.t": "Sıralı",
    "x.mode1.d": "Rastgele rakiple eşleş, puan topla, rütbe atla. Puan ve rütbe hesabı sunucuda yapılıyor.",
    "x.mode2.t": "Kaos",
    "x.mode2.d": "Rastgele üretilen engelli tahtalar. Ezber yok, her maç yeni bir şekil.",
    "x.mode3.t": "Meydan okuma",
    "x.mode3.d": "Yirmi bölüm. Çapraz sayma, ayna, sis, körlük — her bölüm kuralı bir yerinden büküyor.",
    "x.mode4.t": "Tek oyuncu",
    "x.mode4.d": "İnternetsiz oynanır. Bot üç zorlukta; kolayı ısınma, zoru gerçekten zor.",
    "x.feat.title": "Kutunun içinde",
    "x.feat.1": "Arkadaş listesi, sohbet ve maç daveti",
    "x.feat.2": "Sıralama tablosu ve rütbeler",
    "x.feat.3": "Avatar ve arka plan koleksiyonu",
    "x.feat.4": "On dil desteği",
    "x.feat.5": "Google Play ile tek dokunuş giriş",
    "x.feat.6": "Premium ile reklamsız oyun",

    /* Destek sayfası */
    "sup.meta.title": "Destek — Yılkı Games",
    "sup.meta.desc": "Yılkı Games oyunları için destek, hata bildirimi, hesap silme ve sık sorulan sorular.",
    "sup.title": "Destek",
    "sup.sub": "Sorularınızı yanıtlıyoruz — genellikle iki iş günü içinde.",
    "sup.boxBody": "Bir hata bildiriyorsanız kullanıcı adınızı, telefon modelinizi ve sorunun hangi ekranda çıktığını yazın. Varsa ekran görüntüsü ekleyin — çok daha hızlı çözeriz.",
    "faq.label": "Sık sorulan sorular",
    "faq.q1": "Hesabımı nasıl silerim?",
    "faq.a1": "Hesabınıza kayıtlı e-posta adresinden <a href=\"mailto:info@yilkigames.com?subject=Hesap%20silme%20talebi\">info@yilkigames.com</a> adresine “Hesap silme talebi” konulu bir e-posta gönderin. Talebi otuz gün içinde tamamlar ve size dönüş yaparız. Hangi verilerin silindiğini <a href=\"/gizlilik.html#hesap-silme\">gizlilik politikasında</a> ayrıntılı yazdık.",
    "faq.q2": "Şifremi unuttum.",
    "faq.a2": "Giriş ekranındaki şifre sıfırlama bağlantısını kullanın. E-posta gelmediyse spam klasörünüze bakın; yine yoksa bize yazın.",
    "faq.q3": "Premium aldım ama reklamlar hâlâ çıkıyor.",
    "faq.a3": "Üyeliğiniz hesabınıza bağlıdır, cihaza değil. Doğru hesapla giriş yaptığınızdan emin olun ve uygulamayı kapatıp yeniden açın. Sorun sürerse Google Play satın alma numaranızla birlikte bize yazın.",
    "faq.q4": "Bir oyuncuyu nasıl şikâyet ederim?",
    "faq.a4": "Maç geçmişinden veya arkadaş listesinden oyuncunun profilini açın, şikâyet butonuna dokunun ve bir sebep seçin. Şikâyetleri elle inceliyoruz.",
    "faq.q5": "İlerlemem kayboldu.",
    "faq.a5": "Puanınız, rütbeniz ve kozmetikleriniz sunucuda tutulur; aynı hesapla giriş yaptığınızda geri gelir. Meydan okuma modundaki seviye ilerlemesi ise yalnızca cihazda saklanır ve uygulamayı sildiğinizde kaybolur.",
    "faq.q6": "Oyun “bağlantı yok” diyor.",
    "faq.a6": "İnternet bağlantınızı kontrol edip yeniden deneyin. Bağlantı olmadan da çevrimdışı modda tek oyunculu oyun ve meydan okuma açıktır.",
    "faq.q7": "Bir oyuncuyu nasıl engellerim?",
    "faq.a7": "Maç geçmişinden veya arkadaş listenden oyuncunun profilini aç ve ENGELLE'ye dokun. Engellediğin kişi sana mesaj, arkadaşlık isteği veya oyun daveti gönderemez. Engellediklerini Ayarlar → Güvenlik → Engellenen Oyuncular ekranından görebilir ve dilediğin zaman kaldırabilirsin.",
  },

  en: {
    "nav.games": "Games",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Help",
    "foot.join": "Join us",
    "foot.portfolio": "Send your portfolio",
    "foot.legal": "Legal",
    "foot.privacy": "Privacy Policy",
    "foot.terms": "Terms of Service",
    "hero.eyebrow": "Independent game studio",
    "hero.title": "Small rules,<br />deep <em>games</em>.",
    "hero.sub": "We are an independent game studio based in Türkiye. We make games that take a minute to learn and months to master.",
    "hero.cta": "See the games",
    "games.title": "Games",
    "games.note": "Four titles",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Out now",
    "badge.dev": "In development",
    "badge.soon": "Coming soon",
    "xoxd.genre": "Turn-based strategy",
    "xoxd.desc": "A familiar board, a rule you have not played before. Each turn you decide whether to place X or O — both symbols are yours.",
    "xoxd.link": "View the game",
    "inklash.genre": "2D combat",
    "inklash.desc": "Fast, sharp, one-touch clashes.",
    "survive.genre": "Life simulation",
    "survive.desc": "Build a life from scratch. Every decision shapes the next one.",
    "bit.genre": "Trading simulation",
    "bit.desc": "Set up your stall, learn to haggle, become the best in the district.",
    "x.back": "All games",
    "x.eyebrow": "Out now · Android",
    "x.sub": "A familiar board, a rule you have not played before.",
    "x.cta": "Get it on Google Play",
    "x.rule.label": "One rule",
    "x.rule.title": "Both symbols are yours.",
    "x.rule.p1": "In classic tic-tac-toe you are X and your opponent is O. Not here. Every turn, <strong>you</strong> decide which one to place.",
    "x.rule.p2": "Every <strong>X-O-X</strong> line that appears on the board scores for you. Attack and defence collapse into a single move: building a line for yourself opens a door for your opponent. A minute to learn.",
    "x.demo.hint": "Try it — tap the cells",
    "x.demo.score": "points",
    "x.demo.clear": "Clear",
    "x.modes.title": "Four modes",
    "x.modes.note": "One rule, four ways",
    "x.mode1.t": "Ranked",
    "x.mode1.d": "Match with a random opponent, earn points, climb the ranks. Scoring is calculated on the server.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Randomly generated boards with obstacles. Nothing to memorise, a new shape every match.",
    "x.mode3.t": "Challenge",
    "x.mode3.d": "Twenty levels. Diagonals, mirrors, fog, blindness — each one bends the rule somewhere.",
    "x.mode4.t": "Single player",
    "x.mode4.d": "Plays offline. Three bot difficulties; easy is a warm-up, hard is genuinely hard.",
    "x.feat.title": "In the box",
    "x.feat.1": "Friends list, chat and match invites",
    "x.feat.2": "Leaderboard and ranks",
    "x.feat.3": "Avatar and background collection",
    "x.feat.4": "Ten languages",
    "x.feat.5": "One-tap sign-in with Google Play",
    "x.feat.6": "Ad-free play with Premium",

    /* Destek sayfası */
    "sup.meta.title": "Support — Yılkı Games",
    "sup.meta.desc": "Support, bug reports, account deletion and frequently asked questions for Yılkı Games.",
    "sup.title": "Support",
    "sup.sub": "We answer your questions, usually within two working days.",
    "sup.boxBody": "If you are reporting a bug, tell us your username, your phone model and which screen the problem appears on. Attach a screenshot if you have one — it makes the fix much faster.",
    "faq.label": "Frequently asked questions",
    "faq.q1": "How do I delete my account?",
    "faq.a1": "Send an email titled “Account deletion request” to <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> from the address registered to your account. We complete requests within thirty days and confirm by email. The <a href=\"/privacy.html#account-deletion\">privacy policy</a> lists exactly what gets erased.",
    "faq.q2": "I forgot my password.",
    "faq.a2": "Use the password reset link on the sign-in screen. If the email does not arrive, check your spam folder; if it is still missing, write to us.",
    "faq.q3": "I bought premium but I still see ads.",
    "faq.a3": "Your membership is tied to your account, not your device. Make sure you are signed in with the right account, then close and reopen the app. If it persists, write to us with your Google Play order number.",
    "faq.q4": "How do I report a player?",
    "faq.a4": "Open the player's profile from your match history or friend list, tap the report button and choose a reason. We review reports by hand.",
    "faq.q5": "My progress is gone.",
    "faq.a5": "Your points, rank and cosmetics live on the server and come back when you sign in with the same account. Challenge-mode level progress is stored only on your device and is lost if you uninstall the game.",
    "faq.q6": "The game says there is no connection.",
    "faq.a6": "Check your internet connection and try again. Even offline, single-player and challenge mode remain available.",
    "faq.q7": "How do I block a player?",
    "faq.a7": "Open the player's profile from your match history or friend list and tap BLOCK. A blocked player cannot send you messages, friend requests or game invites. You can see and undo your blocks in Settings → Safety → Blocked Players.",
  },

  es: {
    "nav.games": "Juegos",
    "nav.support": "Soporte",
    "foot.studio": "Estudio",
    "foot.help": "Ayuda",
    "foot.join": "Únete",
    "foot.portfolio": "Envía tu portafolio",
    "foot.legal": "Legal",
    "foot.privacy": "Política de privacidad",
    "foot.terms": "Condiciones de uso",
    "hero.eyebrow": "Estudio de videojuegos independiente",
    "hero.title": "Reglas pequeñas,<br />juegos <em>profundos</em>.",
    "hero.sub": "Somos un estudio independiente con sede en Türkiye. Hacemos juegos que se aprenden en un minuto y se dominan en meses.",
    "hero.cta": "Ver los juegos",
    "games.title": "Juegos",
    "games.note": "Cuatro títulos",
    "games.mobile": "Móvil",
    "games.pc": "PC",
    "badge.live": "Disponible",
    "badge.dev": "En desarrollo",
    "badge.soon": "Próximamente",
    "xoxd.genre": "Estrategia por turnos",
    "xoxd.desc": "Un tablero conocido, una regla que no has jugado. En cada turno decides si pones X u O: los dos símbolos son tuyos.",
    "xoxd.link": "Ver el juego",
    "inklash.genre": "Combate 2D",
    "inklash.desc": "Choques rápidos, duros, de un solo toque.",
    "survive.genre": "Simulación de vida",
    "survive.desc": "Construye una vida desde cero. Cada decisión marca la siguiente.",
    "bit.genre": "Simulación de comercio",
    "bit.desc": "Monta tu puesto, aprende a regatear, sé el mejor del barrio.",
    "x.back": "Todos los juegos",
    "x.eyebrow": "Disponible · Android",
    "x.sub": "Un tablero conocido, una regla que no has jugado.",
    "x.cta": "Consíguelo en Google Play",
    "x.rule.label": "Una regla",
    "x.rule.title": "Los dos símbolos son tuyos.",
    "x.rule.p1": "En el tres en raya clásico tú eres X y tu rival es O. Aquí no. En cada turno decides <strong>tú</strong> cuál colocar.",
    "x.rule.p2": "Cada línea <strong>X-O-X</strong> que aparece en el tablero te da puntos. Ataque y defensa se juntan en un mismo movimiento: al construir tu línea le abres la puerta al rival. Un minuto para aprenderlo.",
    "x.demo.hint": "Pruébalo — toca las casillas",
    "x.demo.score": "puntos",
    "x.demo.clear": "Limpiar",
    "x.modes.title": "Cuatro modos",
    "x.modes.note": "Una regla, cuatro caminos",
    "x.mode1.t": "Clasificatoria",
    "x.mode1.d": "Enfréntate a un rival al azar, suma puntos, sube de rango. El cálculo se hace en el servidor.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tableros generados al azar con obstáculos. Nada que memorizar, una forma nueva cada partida.",
    "x.mode3.t": "Desafío",
    "x.mode3.d": "Veinte niveles. Diagonales, espejos, niebla, ceguera: cada uno tuerce la regla por algún lado.",
    "x.mode4.t": "Un jugador",
    "x.mode4.d": "Se juega sin conexión. Tres dificultades; la fácil es un calentamiento, la difícil es difícil de verdad.",
    "x.feat.title": "En la caja",
    "x.feat.1": "Lista de amigos, chat e invitaciones",
    "x.feat.2": "Clasificación y rangos",
    "x.feat.3": "Colección de avatares y fondos",
    "x.feat.4": "Diez idiomas",
    "x.feat.5": "Inicio de sesión con Google Play",
    "x.feat.6": "Sin anuncios con Premium",

    /* Destek sayfası */
    "sup.meta.title": "Soporte — Yılkı Games",
    "sup.meta.desc": "Soporte, informes de errores, eliminación de cuenta y preguntas frecuentes de Yılkı Games.",
    "sup.title": "Soporte",
    "sup.sub": "Respondemos tus preguntas, normalmente en dos días laborables.",
    "sup.boxBody": "Si informas de un error, indícanos tu nombre de usuario, el modelo de tu teléfono y en qué pantalla aparece el problema. Adjunta una captura si la tienes: acelera mucho la solución.",
    "faq.label": "Preguntas frecuentes",
    "faq.q1": "¿Cómo elimino mi cuenta?",
    "faq.a1": "Envía un correo con el asunto “Solicitud de eliminación de cuenta” a <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> desde la dirección registrada en tu cuenta. Completamos las solicitudes en treinta días y te confirmamos por correo. La <a href=\"/privacy.html#account-deletion\">política de privacidad</a> detalla qué se borra.",
    "faq.q2": "He olvidado mi contraseña.",
    "faq.a2": "Usa el enlace de restablecimiento en la pantalla de inicio de sesión. Si el correo no llega, revisa la carpeta de spam; si sigue sin aparecer, escríbenos.",
    "faq.q3": "Compré premium pero sigo viendo anuncios.",
    "faq.a3": "Tu suscripción está vinculada a tu cuenta, no al dispositivo. Comprueba que has iniciado sesión con la cuenta correcta y reinicia la aplicación. Si continúa, escríbenos con tu número de pedido de Google Play.",
    "faq.q4": "¿Cómo denuncio a un jugador?",
    "faq.a4": "Abre el perfil del jugador desde tu historial de partidas o tu lista de amigos, pulsa el botón de denuncia y elige un motivo. Revisamos las denuncias manualmente.",
    "faq.q5": "He perdido mi progreso.",
    "faq.a5": "Tus puntos, tu rango y tus cosméticos se guardan en el servidor y vuelven al iniciar sesión con la misma cuenta. El progreso del modo desafío se guarda solo en tu dispositivo y se pierde si desinstalas el juego.",
    "faq.q6": "El juego dice que no hay conexión.",
    "faq.a6": "Comprueba tu conexión a internet e inténtalo de nuevo. Incluso sin conexión, el modo de un jugador y el modo desafío siguen disponibles.",
    "faq.q7": "¿Cómo bloqueo a un jugador?",
    "faq.a7": "Abre su perfil desde el historial de partidas o tu lista de amigos y toca BLOQUEAR. Un jugador bloqueado no puede enviarte mensajes, solicitudes de amistad ni invitaciones. Puedes ver y deshacer tus bloqueos en Ajustes → Seguridad → Jugadores bloqueados.",
  },

  de: {
    "nav.games": "Spiele",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Hilfe",
    "foot.join": "Mitmachen",
    "foot.portfolio": "Portfolio senden",
    "foot.legal": "Rechtliches",
    "foot.privacy": "Datenschutzerklärung",
    "foot.terms": "Nutzungsbedingungen",
    "hero.eyebrow": "Unabhängiges Spielestudio",
    "hero.title": "Kleine Regeln,<br />tiefe <em>Spiele</em>.",
    "hero.sub": "Wir sind ein unabhängiges Spielestudio in der Türkei. Wir machen Spiele, die man in einer Minute lernt und in Monaten meistert.",
    "hero.cta": "Spiele ansehen",
    "games.title": "Spiele",
    "games.note": "Vier Titel",
    "games.mobile": "Mobil",
    "games.pc": "PC",
    "badge.live": "Jetzt erhältlich",
    "badge.dev": "In Entwicklung",
    "badge.soon": "Demnächst",
    "xoxd.genre": "Rundenbasierte Strategie",
    "xoxd.desc": "Ein bekanntes Brett, eine Regel, die du noch nie gespielt hast. Jede Runde entscheidest du: X oder O — beide Zeichen gehören dir.",
    "xoxd.link": "Spiel ansehen",
    "inklash.genre": "2D-Kampf",
    "inklash.desc": "Schnelle, harte Zusammenstöße mit einem Tipp.",
    "survive.genre": "Lebenssimulation",
    "survive.desc": "Bau ein Leben von Grund auf. Jede Entscheidung prägt die nächste.",
    "bit.genre": "Handelssimulation",
    "bit.desc": "Bau deinen Stand auf, lerne zu feilschen, werde der Beste im Viertel.",
    "x.back": "Alle Spiele",
    "x.eyebrow": "Jetzt erhältlich · Android",
    "x.sub": "Ein bekanntes Brett, eine Regel, die du noch nie gespielt hast.",
    "x.cta": "Bei Google Play holen",
    "x.rule.label": "Eine Regel",
    "x.rule.title": "Beide Zeichen gehören dir.",
    "x.rule.p1": "Beim klassischen Tic-Tac-Toe bist du X und dein Gegner O. Hier nicht. In jeder Runde entscheidest <strong>du</strong>, welches du setzt.",
    "x.rule.p2": "Jede <strong>X-O-X</strong>-Reihe auf dem Brett bringt dir Punkte. Angriff und Verteidigung fallen in einen Zug zusammen: Wer sich eine Reihe baut, öffnet dem Gegner eine Tür. In einer Minute gelernt.",
    "x.demo.hint": "Probier's — tippe die Felder an",
    "x.demo.score": "Punkte",
    "x.demo.clear": "Leeren",
    "x.modes.title": "Vier Modi",
    "x.modes.note": "Eine Regel, vier Wege",
    "x.mode1.t": "Rangliste",
    "x.mode1.d": "Triff auf zufällige Gegner, sammle Punkte, steig im Rang auf. Die Wertung läuft auf dem Server.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Zufällig erzeugte Bretter mit Hindernissen. Nichts zum Auswendiglernen, jede Partie eine neue Form.",
    "x.mode3.t": "Herausforderung",
    "x.mode3.d": "Zwanzig Level. Diagonalen, Spiegel, Nebel, Blindheit — jedes biegt die Regel an einer Stelle.",
    "x.mode4.t": "Einzelspieler",
    "x.mode4.d": "Läuft offline. Drei Bot-Stufen; leicht ist Aufwärmen, schwer ist wirklich schwer.",
    "x.feat.title": "Im Paket",
    "x.feat.1": "Freundesliste, Chat und Spieleinladungen",
    "x.feat.2": "Bestenliste und Ränge",
    "x.feat.3": "Avatar- und Hintergrundsammlung",
    "x.feat.4": "Zehn Sprachen",
    "x.feat.5": "Anmeldung mit einem Tipp über Google Play",
    "x.feat.6": "Werbefrei mit Premium",

    /* Destek sayfası */
    "sup.meta.title": "Support — Yılkı Games",
    "sup.meta.desc": "Support, Fehlermeldungen, Kontolöschung und häufige Fragen zu Yılkı Games.",
    "sup.title": "Support",
    "sup.sub": "Wir beantworten Ihre Fragen, in der Regel innerhalb von zwei Werktagen.",
    "sup.boxBody": "Wenn Sie einen Fehler melden, nennen Sie uns bitte Ihren Benutzernamen, Ihr Telefonmodell und den Bildschirm, auf dem das Problem auftritt. Ein Screenshot beschleunigt die Lösung erheblich.",
    "faq.label": "Häufige Fragen",
    "faq.q1": "Wie lösche ich mein Konto?",
    "faq.a1": "Senden Sie von der bei Ihrem Konto registrierten Adresse eine E-Mail mit dem Betreff „Account deletion request“ an <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a>. Wir bearbeiten Anfragen innerhalb von dreißig Tagen und bestätigen per E-Mail. Was genau gelöscht wird, steht in der <a href=\"/privacy.html#account-deletion\">Datenschutzerklärung</a>.",
    "faq.q2": "Ich habe mein Passwort vergessen.",
    "faq.a2": "Nutzen Sie den Link zum Zurücksetzen auf dem Anmeldebildschirm. Kommt die E-Mail nicht an, prüfen Sie den Spam-Ordner; fehlt sie weiterhin, schreiben Sie uns.",
    "faq.q3": "Ich habe Premium gekauft, sehe aber weiterhin Werbung.",
    "faq.a3": "Ihre Mitgliedschaft ist an Ihr Konto gebunden, nicht an das Gerät. Prüfen Sie, ob Sie mit dem richtigen Konto angemeldet sind, und starten Sie die App neu. Besteht das Problem weiter, schreiben Sie uns mit Ihrer Google-Play-Bestellnummer.",
    "faq.q4": "Wie melde ich einen Spieler?",
    "faq.a4": "Öffnen Sie das Profil des Spielers über den Spielverlauf oder Ihre Freundesliste, tippen Sie auf die Meldefunktion und wählen Sie einen Grund. Wir prüfen Meldungen von Hand.",
    "faq.q5": "Mein Fortschritt ist weg.",
    "faq.a5": "Punkte, Rang und Kosmetik liegen auf dem Server und kehren zurück, sobald Sie sich mit demselben Konto anmelden. Der Fortschritt im Herausforderungsmodus liegt nur auf Ihrem Gerät und geht bei einer Deinstallation verloren.",
    "faq.q6": "Das Spiel meldet „keine Verbindung“.",
    "faq.a6": "Prüfen Sie Ihre Internetverbindung und versuchen Sie es erneut. Auch offline bleiben der Einzelspieler- und der Herausforderungsmodus verfügbar.",
    "faq.q7": "Wie blockiere ich einen Spieler?",
    "faq.a7": "Öffne das Profil über den Spielverlauf oder deine Freundesliste und tippe auf BLOCKIEREN. Blockierte Spieler können dir keine Nachrichten, Freundschaftsanfragen oder Einladungen senden. Unter Einstellungen → Sicherheit → Blockierte Spieler kannst du das jederzeit rückgängig machen.",
  },

  fr: {
    "nav.games": "Jeux",
    "nav.support": "Support",
    "foot.studio": "Studio",
    "foot.help": "Aide",
    "foot.join": "Nous rejoindre",
    "foot.portfolio": "Envoyer ton portfolio",
    "foot.legal": "Mentions légales",
    "foot.privacy": "Politique de confidentialité",
    "foot.terms": "Conditions d'utilisation",
    "hero.eyebrow": "Studio de jeux indépendant",
    "hero.title": "Des règles simples,<br />des jeux <em>profonds</em>.",
    "hero.sub": "Nous sommes un studio indépendant basé en Türkiye. Nous faisons des jeux qui s'apprennent en une minute et se maîtrisent en des mois.",
    "hero.cta": "Voir les jeux",
    "games.title": "Jeux",
    "games.note": "Quatre titres",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponible",
    "badge.dev": "En développement",
    "badge.soon": "Bientôt",
    "xoxd.genre": "Stratégie au tour par tour",
    "xoxd.desc": "Un plateau connu, une règle que tu n'as jamais jouée. À chaque tour, tu choisis X ou O — les deux symboles sont à toi.",
    "xoxd.link": "Voir le jeu",
    "inklash.genre": "Combat 2D",
    "inklash.desc": "Des affrontements rapides et secs, en un seul toucher.",
    "survive.genre": "Simulation de vie",
    "survive.desc": "Construis une vie depuis zéro. Chaque décision décide de la suivante.",
    "bit.genre": "Simulation de commerce",
    "bit.desc": "Monte ton stand, apprends à marchander, deviens le meilleur du quartier.",
    "x.back": "Tous les jeux",
    "x.eyebrow": "Disponible · Android",
    "x.sub": "Un plateau connu, une règle que tu n'as jamais jouée.",
    "x.cta": "Télécharger sur Google Play",
    "x.rule.label": "Une seule règle",
    "x.rule.title": "Les deux symboles sont à toi.",
    "x.rule.p1": "Au morpion classique, tu es X et ton adversaire O. Ici, non. À chaque tour, c'est <strong>toi</strong> qui choisis lequel poser.",
    "x.rule.p2": "Chaque ligne <strong>X-O-X</strong> qui apparaît sur le plateau te rapporte des points. L'attaque et la défense se confondent en un seul coup : en te construisant une ligne, tu ouvres une porte à l'adversaire. Une minute pour comprendre.",
    "x.demo.hint": "Essaie — touche les cases",
    "x.demo.score": "points",
    "x.demo.clear": "Effacer",
    "x.modes.title": "Quatre modes",
    "x.modes.note": "Une règle, quatre chemins",
    "x.mode1.t": "Classée",
    "x.mode1.d": "Affronte un adversaire au hasard, gagne des points, monte en rang. Le calcul se fait sur le serveur.",
    "x.mode2.t": "Chaos",
    "x.mode2.d": "Plateaux générés au hasard avec des obstacles. Rien à mémoriser, une forme nouvelle à chaque partie.",
    "x.mode3.t": "Défi",
    "x.mode3.d": "Vingt niveaux. Diagonales, miroirs, brouillard, cécité — chacun tord la règle quelque part.",
    "x.mode4.t": "Solo",
    "x.mode4.d": "Se joue hors ligne. Trois niveaux de bot ; le facile est un échauffement, le difficile est vraiment difficile.",
    "x.feat.title": "Dans la boîte",
    "x.feat.1": "Liste d'amis, chat et invitations",
    "x.feat.2": "Classement et rangs",
    "x.feat.3": "Collection d'avatars et de fonds",
    "x.feat.4": "Dix langues",
    "x.feat.5": "Connexion en un toucher avec Google Play",
    "x.feat.6": "Sans publicité avec Premium",

    /* Destek sayfası */
    "sup.meta.title": "Assistance — Yılkı Games",
    "sup.meta.desc": "Assistance, rapports de bugs, suppression de compte et questions fréquentes pour Yılkı Games.",
    "sup.title": "Assistance",
    "sup.sub": "Nous répondons à vos questions, généralement sous deux jours ouvrés.",
    "sup.boxBody": "Si vous signalez un bug, indiquez votre nom d’utilisateur, le modèle de votre téléphone et l’écran où le problème apparaît. Joignez une capture d’écran si vous en avez une : la résolution sera bien plus rapide.",
    "faq.label": "Questions fréquentes",
    "faq.q1": "Comment supprimer mon compte ?",
    "faq.a1": "Envoyez un e-mail intitulé « Account deletion request » à <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> depuis l’adresse enregistrée sur votre compte. Nous traitons les demandes sous trente jours et confirmons par e-mail. La <a href=\"/privacy.html#account-deletion\">politique de confidentialité</a> détaille ce qui est effacé.",
    "faq.q2": "J’ai oublié mon mot de passe.",
    "faq.a2": "Utilisez le lien de réinitialisation sur l’écran de connexion. Si l’e-mail n’arrive pas, vérifiez vos courriers indésirables ; s’il reste introuvable, écrivez-nous.",
    "faq.q3": "J’ai acheté le premium mais je vois encore des publicités.",
    "faq.a3": "Votre abonnement est lié à votre compte, pas à votre appareil. Vérifiez que vous êtes connecté avec le bon compte, puis relancez l’application. Si le problème persiste, écrivez-nous avec votre numéro de commande Google Play.",
    "faq.q4": "Comment signaler un joueur ?",
    "faq.a4": "Ouvrez le profil du joueur depuis l’historique des parties ou votre liste d’amis, appuyez sur le bouton de signalement et choisissez un motif. Nous examinons les signalements à la main.",
    "faq.q5": "J’ai perdu ma progression.",
    "faq.a5": "Vos points, votre rang et vos cosmétiques sont conservés sur le serveur et reviennent dès que vous vous connectez avec le même compte. La progression du mode défi est stockée uniquement sur votre appareil et disparaît si vous désinstallez le jeu.",
    "faq.q6": "Le jeu indique « pas de connexion ».",
    "faq.a6": "Vérifiez votre connexion internet puis réessayez. Même hors ligne, le mode solo et le mode défi restent accessibles.",
    "faq.q7": "Comment bloquer un joueur ?",
    "faq.a7": "Ouvre son profil depuis l'historique des parties ou ta liste d'amis et appuie sur BLOQUER. Un joueur bloqué ne peut plus t'envoyer de messages, de demandes d'ami ni d'invitations. Tu peux gérer tes blocages dans Paramètres → Sécurité → Joueurs bloqués.",
  },

  it: {
    "nav.games": "Giochi",
    "nav.support": "Supporto",
    "foot.studio": "Studio",
    "foot.help": "Aiuto",
    "foot.join": "Unisciti a noi",
    "foot.portfolio": "Invia il portfolio",
    "foot.legal": "Note legali",
    "foot.privacy": "Informativa sulla privacy",
    "foot.terms": "Termini di servizio",
    "hero.eyebrow": "Studio di giochi indipendente",
    "hero.title": "Regole piccole,<br />giochi <em>profondi</em>.",
    "hero.sub": "Siamo uno studio indipendente con sede in Türkiye. Facciamo giochi che si imparano in un minuto e si padroneggiano in mesi.",
    "hero.cta": "Guarda i giochi",
    "games.title": "Giochi",
    "games.note": "Quattro titoli",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponibile",
    "badge.dev": "In sviluppo",
    "badge.soon": "In arrivo",
    "xoxd.genre": "Strategia a turni",
    "xoxd.desc": "Una tavola familiare, una regola che non hai mai giocato. Ogni turno decidi tu se mettere X o O: entrambi i simboli sono tuoi.",
    "xoxd.link": "Guarda il gioco",
    "inklash.genre": "Combattimento 2D",
    "inklash.desc": "Scontri rapidi e secchi, con un solo tocco.",
    "survive.genre": "Simulazione di vita",
    "survive.desc": "Costruisci una vita da zero. Ogni scelta determina la successiva.",
    "bit.genre": "Simulazione di commercio",
    "bit.desc": "Monta il banco, impara a contrattare, diventa il migliore del quartiere.",
    "x.back": "Tutti i giochi",
    "x.eyebrow": "Disponibile · Android",
    "x.sub": "Una tavola familiare, una regola che non hai mai giocato.",
    "x.cta": "Scarica su Google Play",
    "x.rule.label": "Una regola",
    "x.rule.title": "Entrambi i simboli sono tuoi.",
    "x.rule.p1": "Nel tris classico tu sei X e l'avversario è O. Qui no. A ogni turno decidi <strong>tu</strong> quale mettere.",
    "x.rule.p2": "Ogni sequenza <strong>X-O-X</strong> che compare sulla tavola ti dà punti. Attacco e difesa si fondono in una sola mossa: mentre costruisci la tua linea, apri una porta all'avversario. Si impara in un minuto.",
    "x.demo.hint": "Prova — tocca le caselle",
    "x.demo.score": "punti",
    "x.demo.clear": "Pulisci",
    "x.modes.title": "Quattro modalità",
    "x.modes.note": "Una regola, quattro strade",
    "x.mode1.t": "Classificata",
    "x.mode1.d": "Sfida un avversario casuale, accumula punti, sali di grado. Il calcolo avviene sul server.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tavole generate a caso con ostacoli. Niente da memorizzare, una forma nuova ogni partita.",
    "x.mode3.t": "Sfida",
    "x.mode3.d": "Venti livelli. Diagonali, specchi, nebbia, cecità: ognuno piega la regola da qualche parte.",
    "x.mode4.t": "Giocatore singolo",
    "x.mode4.d": "Si gioca offline. Tre difficoltà; la facile è riscaldamento, la difficile è davvero difficile.",
    "x.feat.title": "Nella scatola",
    "x.feat.1": "Lista amici, chat e inviti alle partite",
    "x.feat.2": "Classifica e gradi",
    "x.feat.3": "Collezione di avatar e sfondi",
    "x.feat.4": "Dieci lingue",
    "x.feat.5": "Accesso con un tocco tramite Google Play",
    "x.feat.6": "Senza pubblicità con Premium",

    /* Destek sayfası */
    "sup.meta.title": "Assistenza — Yılkı Games",
    "sup.meta.desc": "Assistenza, segnalazioni, eliminazione dell’account e domande frequenti su Yılkı Games.",
    "sup.title": "Assistenza",
    "sup.sub": "Rispondiamo alle tue domande, di solito entro due giorni lavorativi.",
    "sup.boxBody": "Se segnali un problema, indicaci il tuo nome utente, il modello del telefono e la schermata in cui si presenta. Allega uno screenshot se ce l’hai: la soluzione arriva molto più in fretta.",
    "faq.label": "Domande frequenti",
    "faq.q1": "Come elimino il mio account?",
    "faq.a1": "Invia un’email con oggetto “Account deletion request” a <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> dall’indirizzo registrato sul tuo account. Completiamo le richieste entro trenta giorni e confermiamo via email. L’<a href=\"/privacy.html#account-deletion\">informativa privacy</a> elenca esattamente cosa viene cancellato.",
    "faq.q2": "Ho dimenticato la password.",
    "faq.a2": "Usa il link di reimpostazione nella schermata di accesso. Se l’email non arriva, controlla la posta indesiderata; se non c’è nemmeno lì, scrivici.",
    "faq.q3": "Ho comprato premium ma vedo ancora la pubblicità.",
    "faq.a3": "L’abbonamento è legato all’account, non al dispositivo. Verifica di aver effettuato l’accesso con l’account giusto e riavvia l’app. Se il problema persiste, scrivici indicando il numero d’ordine di Google Play.",
    "faq.q4": "Come segnalo un giocatore?",
    "faq.a4": "Apri il profilo del giocatore dalla cronologia delle partite o dalla lista amici, tocca il pulsante di segnalazione e scegli un motivo. Esaminiamo le segnalazioni a mano.",
    "faq.q5": "Ho perso i miei progressi.",
    "faq.a5": "Punti, grado e oggetti estetici sono salvati sul server e tornano quando accedi con lo stesso account. I progressi della modalità sfida restano solo sul dispositivo e si perdono disinstallando il gioco.",
    "faq.q6": "Il gioco dice che non c’è connessione.",
    "faq.a6": "Controlla la connessione a internet e riprova. Anche offline restano disponibili la modalità a giocatore singolo e la modalità sfida.",
    "faq.q7": "Come blocco un giocatore?",
    "faq.a7": "Apri il suo profilo dalla cronologia delle partite o dalla lista amici e tocca BLOCCA. Un giocatore bloccato non può inviarti messaggi, richieste di amicizia o inviti. Puoi gestire i blocchi in Impostazioni → Sicurezza → Giocatori bloccati.",
  },

  pt: {
    "nav.games": "Jogos",
    "nav.support": "Suporte",
    "foot.studio": "Estúdio",
    "foot.help": "Ajuda",
    "foot.join": "Junte-se a nós",
    "foot.portfolio": "Envie seu portfólio",
    "foot.legal": "Jurídico",
    "foot.privacy": "Política de Privacidade",
    "foot.terms": "Termos de Uso",
    "hero.eyebrow": "Estúdio de jogos independente",
    "hero.title": "Regras pequenas,<br />jogos <em>profundos</em>.",
    "hero.sub": "Somos um estúdio independente sediado na Türkiye. Fazemos jogos que se aprendem em um minuto e se dominam em meses.",
    "hero.cta": "Ver os jogos",
    "games.title": "Jogos",
    "games.note": "Quatro títulos",
    "games.mobile": "Mobile",
    "games.pc": "PC",
    "badge.live": "Disponível",
    "badge.dev": "Em desenvolvimento",
    "badge.soon": "Em breve",
    "xoxd.genre": "Estratégia por turnos",
    "xoxd.desc": "Um tabuleiro conhecido, uma regra que você nunca jogou. A cada turno você decide se coloca X ou O — os dois símbolos são seus.",
    "xoxd.link": "Ver o jogo",
    "inklash.genre": "Combate 2D",
    "inklash.desc": "Choques rápidos e secos, com um toque só.",
    "survive.genre": "Simulação de vida",
    "survive.desc": "Construa uma vida do zero. Cada decisão define a próxima.",
    "bit.genre": "Simulação de comércio",
    "bit.desc": "Monte sua banca, aprenda a pechinchar, seja o melhor do bairro.",
    "x.back": "Todos os jogos",
    "x.eyebrow": "Disponível · Android",
    "x.sub": "Um tabuleiro conhecido, uma regra que você nunca jogou.",
    "x.cta": "Baixar no Google Play",
    "x.rule.label": "Uma regra",
    "x.rule.title": "Os dois símbolos são seus.",
    "x.rule.p1": "No jogo da velha clássico você é X e o adversário é O. Aqui não. A cada turno, <strong>você</strong> decide qual colocar.",
    "x.rule.p2": "Cada sequência <strong>X-O-X</strong> que aparece no tabuleiro te dá pontos. Ataque e defesa viram uma jogada só: ao montar sua linha, você abre uma porta para o adversário. Um minuto para aprender.",
    "x.demo.hint": "Experimente — toque nas casas",
    "x.demo.score": "pontos",
    "x.demo.clear": "Limpar",
    "x.modes.title": "Quatro modos",
    "x.modes.note": "Uma regra, quatro caminhos",
    "x.mode1.t": "Ranqueada",
    "x.mode1.d": "Enfrente um adversário aleatório, some pontos, suba de patente. O cálculo é feito no servidor.",
    "x.mode2.t": "Caos",
    "x.mode2.d": "Tabuleiros gerados ao acaso com obstáculos. Nada para decorar, uma forma nova a cada partida.",
    "x.mode3.t": "Desafio",
    "x.mode3.d": "Vinte fases. Diagonais, espelhos, névoa, cegueira — cada uma torce a regra em algum ponto.",
    "x.mode4.t": "Um jogador",
    "x.mode4.d": "Joga offline. Três dificuldades; a fácil é aquecimento, a difícil é difícil de verdade.",
    "x.feat.title": "Na caixa",
    "x.feat.1": "Lista de amigos, chat e convites",
    "x.feat.2": "Classificação e patentes",
    "x.feat.3": "Coleção de avatares e fundos",
    "x.feat.4": "Dez idiomas",
    "x.feat.5": "Login com um toque pelo Google Play",
    "x.feat.6": "Sem anúncios com o Premium",

    /* Destek sayfası */
    "sup.meta.title": "Suporte — Yılkı Games",
    "sup.meta.desc": "Suporte, relatos de erros, eliminação de conta e perguntas frequentes da Yılkı Games.",
    "sup.title": "Suporte",
    "sup.sub": "Respondemos às suas perguntas, normalmente em dois dias úteis.",
    "sup.boxBody": "Se está a comunicar um erro, indique o seu nome de utilizador, o modelo do telemóvel e o ecrã em que o problema aparece. Junte uma captura de ecrã, se tiver — acelera muito a resolução.",
    "faq.label": "Perguntas frequentes",
    "faq.q1": "Como elimino a minha conta?",
    "faq.a1": "Envie um email com o assunto “Account deletion request” para <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> a partir do endereço registado na sua conta. Concluímos os pedidos em trinta dias e confirmamos por email. A <a href=\"/privacy.html#account-deletion\">política de privacidade</a> indica exatamente o que é apagado.",
    "faq.q2": "Esqueci-me da palavra-passe.",
    "faq.a2": "Use a ligação de reposição no ecrã de início de sessão. Se o email não chegar, verifique a pasta de spam; se continuar em falta, escreva-nos.",
    "faq.q3": "Comprei premium mas continuo a ver anúncios.",
    "faq.a3": "A subscrição está ligada à sua conta, não ao dispositivo. Confirme que iniciou sessão com a conta certa e reinicie a aplicação. Se persistir, escreva-nos com o número de encomenda da Google Play.",
    "faq.q4": "Como denuncio um jogador?",
    "faq.a4": "Abra o perfil do jogador a partir do histórico de partidas ou da lista de amigos, toque no botão de denúncia e escolha um motivo. Analisamos as denúncias manualmente.",
    "faq.q5": "Perdi o meu progresso.",
    "faq.a5": "Os seus pontos, patente e cosméticos ficam no servidor e regressam quando inicia sessão com a mesma conta. O progresso do modo desafio fica apenas no dispositivo e perde-se se desinstalar o jogo.",
    "faq.q6": "O jogo diz que não há ligação.",
    "faq.a6": "Verifique a ligação à internet e tente novamente. Mesmo sem ligação, o modo de um jogador e o modo desafio continuam disponíveis.",
    "faq.q7": "Como bloqueio um jogador?",
    "faq.a7": "Abra o perfil pelo histórico de partidas ou pela lista de amigos e toque em BLOQUEAR. Um jogador bloqueado não pode enviar-lhe mensagens, pedidos de amizade ou convites. Pode gerir os bloqueios em Definições → Segurança → Jogadores bloqueados.",
  },

  ru: {
    "nav.games": "Игры",
    "nav.support": "Поддержка",
    "foot.studio": "Студия",
    "foot.help": "Помощь",
    "foot.join": "Присоединяйся",
    "foot.portfolio": "Отправить портфолио",
    "foot.legal": "Правовая информация",
    "foot.privacy": "Политика конфиденциальности",
    "foot.terms": "Условия использования",
    "hero.eyebrow": "Независимая игровая студия",
    "hero.title": "Простые правила,<br />глубокие <em>игры</em>.",
    "hero.sub": "Мы независимая игровая студия из Турции. Делаем игры, которые осваиваются за минуту, а изучаются месяцами.",
    "hero.cta": "Посмотреть игры",
    "games.title": "Игры",
    "games.note": "Четыре проекта",
    "games.mobile": "Мобильные",
    "games.pc": "PC",
    "badge.live": "Уже вышла",
    "badge.dev": "В разработке",
    "badge.soon": "Скоро",
    "xoxd.genre": "Пошаговая стратегия",
    "xoxd.desc": "Знакомая доска и правило, в которое ты ещё не играл. Каждый ход ты сам решаешь, ставить X или O — оба символа твои.",
    "xoxd.link": "Об игре",
    "inklash.genre": "2D-бои",
    "inklash.desc": "Быстрые и жёсткие схватки в одно касание.",
    "survive.genre": "Симулятор жизни",
    "survive.desc": "Построй жизнь с нуля. Каждое решение определяет следующее.",
    "bit.genre": "Симулятор торговли",
    "bit.desc": "Поставь прилавок, научись торговаться, стань лучшим в районе.",
    "x.back": "Все игры",
    "x.eyebrow": "Уже вышла · Android",
    "x.sub": "Знакомая доска и правило, в которое ты ещё не играл.",
    "x.cta": "Скачать в Google Play",
    "x.rule.label": "Одно правило",
    "x.rule.title": "Оба символа твои.",
    "x.rule.p1": "В классических крестиках-ноликах ты X, а соперник O. Здесь не так. Каждый ход <strong>ты</strong> решаешь, что поставить.",
    "x.rule.p2": "Каждая последовательность <strong>X-O-X</strong> на доске приносит тебе очки. Атака и защита сливаются в один ход: строя свою линию, ты открываешь дверь сопернику. Разобраться — минута.",
    "x.demo.hint": "Попробуй — нажимай на клетки",
    "x.demo.score": "очков",
    "x.demo.clear": "Очистить",
    "x.modes.title": "Четыре режима",
    "x.modes.note": "Одно правило, четыре пути",
    "x.mode1.t": "Рейтинговый",
    "x.mode1.d": "Играй со случайным соперником, набирай очки, поднимай ранг. Подсчёт идёт на сервере.",
    "x.mode2.t": "Хаос",
    "x.mode2.d": "Случайные доски с препятствиями. Заучивать нечего, каждая партия — новая форма.",
    "x.mode3.t": "Испытание",
    "x.mode3.d": "Двадцать уровней. Диагонали, зеркала, туман, слепота — каждый где-то ломает правило.",
    "x.mode4.t": "Одиночная игра",
    "x.mode4.d": "Работает без интернета. Три уровня бота: лёгкий — разминка, сложный — действительно сложный.",
    "x.feat.title": "Что внутри",
    "x.feat.1": "Список друзей, чат и приглашения",
    "x.feat.2": "Таблица лидеров и ранги",
    "x.feat.3": "Коллекция аватаров и фонов",
    "x.feat.4": "Десять языков",
    "x.feat.5": "Вход одним касанием через Google Play",
    "x.feat.6": "Без рекламы с Премиумом",

    /* Destek sayfası */
    "sup.meta.title": "Поддержка — Yılkı Games",
    "sup.meta.desc": "Поддержка, сообщения об ошибках, удаление аккаунта и частые вопросы Yılkı Games.",
    "sup.title": "Поддержка",
    "sup.sub": "Мы отвечаем на вопросы, обычно в течение двух рабочих дней.",
    "sup.boxBody": "Если вы сообщаете об ошибке, укажите имя пользователя, модель телефона и экран, на котором возникает проблема. Приложите скриншот, если он есть, — так мы решим вопрос гораздо быстрее.",
    "faq.label": "Частые вопросы",
    "faq.q1": "Как удалить аккаунт?",
    "faq.a1": "Отправьте письмо с темой «Account deletion request» на адрес <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> с электронной почты, привязанной к аккаунту. Мы выполняем запросы в течение тридцати дней и подтверждаем по почте. Что именно удаляется, описано в <a href=\"/privacy.html#account-deletion\">политике конфиденциальности</a>.",
    "faq.q2": "Я забыл пароль.",
    "faq.a2": "Воспользуйтесь ссылкой для сброса пароля на экране входа. Если письмо не пришло, проверьте папку со спамом; если его там нет, напишите нам.",
    "faq.q3": "Я купил премиум, но реклама всё равно показывается.",
    "faq.a3": "Подписка привязана к аккаунту, а не к устройству. Убедитесь, что вы вошли в нужный аккаунт, и перезапустите приложение. Если проблема осталась, напишите нам и укажите номер заказа в Google Play.",
    "faq.q4": "Как пожаловаться на игрока?",
    "faq.a4": "Откройте профиль игрока из истории матчей или списка друзей, нажмите кнопку жалобы и выберите причину. Жалобы мы разбираем вручную.",
    "faq.q5": "Мой прогресс пропал.",
    "faq.a5": "Очки, ранг и косметика хранятся на сервере и вернутся, когда вы войдёте в тот же аккаунт. Прогресс режима испытаний хранится только на устройстве и теряется при удалении игры.",
    "faq.q6": "Игра пишет, что нет соединения.",
    "faq.a6": "Проверьте подключение к интернету и повторите попытку. Даже без сети доступны одиночная игра и режим испытаний.",
    "faq.q7": "Как заблокировать игрока?",
    "faq.a7": "Откройте профиль игрока из истории матчей или списка друзей и нажмите ЗАБЛОКИРОВАТЬ. Заблокированный игрок не сможет отправлять вам сообщения, заявки в друзья и приглашения. Управлять блокировками можно в разделе Настройки → Безопасность → Заблокированные игроки.",
  },

  zh: {
    "nav.games": "游戏",
    "nav.support": "支持",
    "foot.studio": "工作室",
    "foot.help": "帮助",
    "foot.join": "加入我们",
    "foot.portfolio": "发送作品集",
    "foot.legal": "法律",
    "foot.privacy": "隐私政策",
    "foot.terms": "使用条款",
    "hero.eyebrow": "独立游戏工作室",
    "hero.title": "规则很小，<br />游戏很<em>深</em>。",
    "hero.sub": "我们是一家位于土耳其的独立游戏工作室。我们做的游戏一分钟上手，几个月才能精通。",
    "hero.cta": "查看游戏",
    "games.title": "游戏",
    "games.note": "四款作品",
    "games.mobile": "移动端",
    "games.pc": "PC",
    "badge.live": "已上线",
    "badge.dev": "开发中",
    "badge.soon": "即将推出",
    "xoxd.genre": "回合制策略",
    "xoxd.desc": "熟悉的棋盘，从未玩过的规则。每回合由你决定下 X 还是 O——两个符号都是你的。",
    "xoxd.link": "查看游戏",
    "inklash.genre": "2D 格斗",
    "inklash.desc": "快速、凌厉、一触即发的对撞。",
    "survive.genre": "人生模拟",
    "survive.desc": "从零开始经营一段人生。每个决定都决定下一个。",
    "bit.genre": "交易模拟",
    "bit.desc": "支起摊位，学会讨价还价，成为街区最强。",
    "x.back": "全部游戏",
    "x.eyebrow": "已上线 · Android",
    "x.sub": "熟悉的棋盘，从未玩过的规则。",
    "x.cta": "在 Google Play 下载",
    "x.rule.label": "唯一规则",
    "x.rule.title": "两个符号都是你的。",
    "x.rule.p1": "在传统井字棋里你是 X，对手是 O。这里不是。每一回合都由<strong>你</strong>决定下哪一个。",
    "x.rule.p2": "棋盘上出现的每一条 <strong>X-O-X</strong> 都会为你计分。进攻和防守合成同一步：你在给自己连线的同时，也给对手开了一扇门。一分钟就能学会。",
    "x.demo.hint": "试试看——点击格子",
    "x.demo.score": "分",
    "x.demo.clear": "清空",
    "x.modes.title": "四种模式",
    "x.modes.note": "一条规则，四条路",
    "x.mode1.t": "排位",
    "x.mode1.d": "匹配随机对手，累积分数，提升段位。计分在服务器完成。",
    "x.mode2.t": "混沌",
    "x.mode2.d": "随机生成的带障碍棋盘。无需背板，每局都是新形状。",
    "x.mode3.t": "挑战",
    "x.mode3.d": "二十个关卡。对角线、镜像、迷雾、致盲——每关都在某处扭曲规则。",
    "x.mode4.t": "单人",
    "x.mode4.d": "可离线游玩。机器人分三档；简单是热身，困难是真的难。",
    "x.feat.title": "包含内容",
    "x.feat.1": "好友列表、聊天与对战邀请",
    "x.feat.2": "排行榜与段位",
    "x.feat.3": "头像与背景收藏",
    "x.feat.4": "十种语言",
    "x.feat.5": "通过 Google Play 一键登录",
    "x.feat.6": "高级版免广告",

    /* Destek sayfası */
    "sup.meta.title": "支持 — Yılkı Games",
    "sup.meta.desc": "Yılkı Games 的技术支持、问题反馈、账号删除与常见问题。",
    "sup.title": "支持",
    "sup.sub": "我们会回复您的问题，通常在两个工作日内。",
    "sup.boxBody": "反馈问题时，请告诉我们您的用户名、手机型号，以及问题出现在哪个界面。如果有截图请一并附上，这样能快得多。",
    "faq.label": "常见问题",
    "faq.q1": "如何删除我的账号？",
    "faq.a1": "请使用账号注册时的邮箱，向 <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> 发送一封主题为「Account deletion request」的邮件。我们会在三十天内处理完毕并回复确认。具体删除哪些数据，请见<a href=\"/privacy.html#account-deletion\">隐私政策</a>。",
    "faq.q2": "我忘记密码了。",
    "faq.a2": "请使用登录界面的密码重置链接。如果没有收到邮件，请检查垃圾邮件文件夹；仍然找不到就写信给我们。",
    "faq.q3": "我买了高级会员，但还是有广告。",
    "faq.a3": "会员绑定的是账号而非设备。请确认登录的是正确的账号，然后重启应用。若问题依旧，请附上 Google Play 订单号写信给我们。",
    "faq.q4": "如何举报玩家？",
    "faq.a4": "在对战记录或好友列表中打开该玩家的资料，点击举报按钮并选择理由。所有举报都由人工审核。",
    "faq.q5": "我的进度不见了。",
    "faq.a5": "积分、段位和外观保存在服务器上，用同一账号登录即可恢复。挑战模式的关卡进度只保存在本机，卸载游戏后会丢失。",
    "faq.q6": "游戏提示没有网络连接。",
    "faq.a6": "请检查网络连接后重试。即使离线，单人模式和挑战模式仍然可以游玩。",
    "faq.q7": "如何屏蔽一位玩家？",
    "faq.a7": "在对战记录或好友列表中打开该玩家的个人资料，点击「屏蔽」。被屏蔽的玩家无法向你发送消息、好友请求或对战邀请。你可以在 设置 → 安全 → 已屏蔽的玩家 中查看并随时解除屏蔽。",
  },

  ja: {
    "nav.games": "ゲーム",
    "nav.support": "サポート",
    "foot.studio": "スタジオ",
    "foot.help": "ヘルプ",
    "foot.join": "参加する",
    "foot.portfolio": "ポートフォリオを送る",
    "foot.legal": "法的情報",
    "foot.privacy": "プライバシーポリシー",
    "foot.terms": "利用規約",
    "hero.eyebrow": "インディーゲームスタジオ",
    "hero.title": "小さなルール、<br />深い<em>ゲーム</em>。",
    "hero.sub": "トルコを拠点とするインディーゲームスタジオです。覚えるのは一分、極めるのは数か月かかるゲームを作っています。",
    "hero.cta": "ゲームを見る",
    "games.title": "ゲーム",
    "games.note": "4タイトル",
    "games.mobile": "モバイル",
    "games.pc": "PC",
    "badge.live": "配信中",
    "badge.dev": "開発中",
    "badge.soon": "近日公開",
    "xoxd.genre": "ターン制ストラテジー",
    "xoxd.desc": "見慣れた盤に、遊んだことのないルール。毎ターン X と O のどちらを置くかは自分次第——どちらの記号もあなたのものです。",
    "xoxd.link": "ゲームを見る",
    "inklash.genre": "2D対戦アクション",
    "inklash.desc": "速く、鋭い、ワンタッチの斬り合い。",
    "survive.genre": "人生シミュレーション",
    "survive.desc": "人生をゼロから組み立てる。すべての選択が次を決めます。",
    "bit.genre": "商売シミュレーション",
    "bit.desc": "露店を構え、値切りを覚え、街で一番になろう。",
    "x.back": "すべてのゲーム",
    "x.eyebrow": "配信中 · Android",
    "x.sub": "見慣れた盤に、遊んだことのないルール。",
    "x.cta": "Google Play で入手",
    "x.rule.label": "ルールはひとつ",
    "x.rule.title": "どちらの記号もあなたのもの。",
    "x.rule.p1": "普通の三目並べでは自分が X、相手が O です。ここでは違います。毎ターン、どちらを置くかを決めるのは<strong>あなた</strong>です。",
    "x.rule.p2": "盤上にできた <strong>X-O-X</strong> の並びがすべて得点になります。攻めと守りが一手に重なる——自分の列を作ることが、相手にも道を開くのです。覚えるのは一分。",
    "x.demo.hint": "試してみよう — マスをタップ",
    "x.demo.score": "点",
    "x.demo.clear": "クリア",
    "x.modes.title": "4つのモード",
    "x.modes.note": "ひとつのルール、4つの遊び方",
    "x.mode1.t": "ランク戦",
    "x.mode1.d": "ランダムな相手と対戦し、ポイントを稼ぎ、ランクを上げる。集計はサーバー側で行われます。",
    "x.mode2.t": "カオス",
    "x.mode2.d": "障害物付きのランダム生成盤面。暗記は不要、毎試合が新しい形です。",
    "x.mode3.t": "チャレンジ",
    "x.mode3.d": "20ステージ。斜め、ミラー、霧、目隠し——それぞれがルールをどこかで曲げます。",
    "x.mode4.t": "シングルプレイ",
    "x.mode4.d": "オフラインで遊べます。ボットは3段階、簡単は肩慣らし、難しいは本当に難しい。",
    "x.feat.title": "収録内容",
    "x.feat.1": "フレンドリスト・チャット・対戦招待",
    "x.feat.2": "ランキングとランク",
    "x.feat.3": "アバターと背景のコレクション",
    "x.feat.4": "10言語対応",
    "x.feat.5": "Google Play でワンタップログイン",
    "x.feat.6": "プレミアムで広告なし",

    /* Destek sayfası */
    "sup.meta.title": "サポート — Yılkı Games",
    "sup.meta.desc": "Yılkı Games のサポート、不具合のご報告、アカウント削除、よくある質問。",
    "sup.title": "サポート",
    "sup.sub": "ご質問には通常、二営業日以内にお答えします。",
    "sup.boxBody": "不具合をご報告いただく際は、ユーザー名、端末の機種、問題が出る画面をお知らせください。スクリーンショットを添えていただけると解決がずっと早くなります。",
    "faq.label": "よくある質問",
    "faq.q1": "アカウントを削除するには？",
    "faq.a1": "アカウントに登録されているメールアドレスから、件名を「Account deletion request」として <a href=\"mailto:info@yilkigames.com?subject=Account%20deletion%20request\">info@yilkigames.com</a> 宛にご連絡ください。三十日以内に対応し、完了をメールでお知らせします。削除される内容は<a href=\"/privacy.html#account-deletion\">プライバシーポリシー</a>に記載しています。",
    "faq.q2": "パスワードを忘れました。",
    "faq.a2": "ログイン画面のパスワード再設定リンクをご利用ください。メールが届かない場合は迷惑メールフォルダをご確認のうえ、それでも見つからなければご連絡ください。",
    "faq.q3": "プレミアムを購入したのに広告が表示されます。",
    "faq.a3": "プレミアムは端末ではなくアカウントに紐づいています。正しいアカウントでログインしているかご確認のうえ、アプリを再起動してください。解決しない場合は Google Play の注文番号を添えてご連絡ください。",
    "faq.q4": "プレイヤーを通報するには？",
    "faq.a4": "対戦履歴またはフレンドリストからそのプレイヤーのプロフィールを開き、通報ボタンを押して理由を選んでください。通報はすべて手作業で確認しています。",
    "faq.q5": "進行状況が消えました。",
    "faq.a5": "ポイント、ランク、装飾はサーバーに保存されており、同じアカウントでログインすれば元に戻ります。チャレンジモードの進行状況は端末内にのみ保存され、アンインストールすると失われます。",
    "faq.q6": "「接続がありません」と表示されます。",
    "faq.a6": "インターネット接続をご確認のうえ、もう一度お試しください。オフラインでもシングルプレイとチャレンジモードはお楽しみいただけます。",
    "faq.q7": "プレイヤーをブロックするには？",
    "faq.a7": "対戦履歴かフレンドリストから相手のプロフィールを開き、「ブロック」をタップします。ブロックした相手はメッセージ・フレンド申請・対戦招待を送れません。設定 → 安全 → ブロックしたプレイヤー でいつでも確認・解除できます。",
  },
};
